package com.moon.quizsnack

import com.moon.quizdrink.R

class Const {
    val thumbnail = arrayOf(
        R.drawable.ambasa,
        R.drawable.bacas,
        R.drawable.bae,
        R.drawable.banana,
        R.drawable.bejimil,
        R.drawable.bita500,
        R.drawable.bosung,
        R.drawable.choco,
        R.drawable.cocacola,
        R.drawable.cocopam,
        R.drawable.confidance,
        R.drawable.demisoda,
        R.drawable.dorage,
        R.drawable.fanta,
        R.drawable.gana,
        R.drawable.gegoa,
        R.drawable.green,
        R.drawable.honny,
        R.drawable.hotsix,
        R.drawable.jejuorange,
        R.drawable.lemonade,
        R.drawable.mccol,
        R.drawable.milkis,
        R.drawable.minitmade,
        R.drawable.moga,
        R.drawable.mountaindew,
        R.drawable.oksusu,
        R.drawable.oranc,
        R.drawable.pocari,
        R.drawable.powerade,
        R.drawable.pro2,
        R.drawable.saida,
        R.drawable.sikhye,
        R.drawable.sprite,
        R.drawable.sunny,
        R.drawable.top,
        R.drawable.welchis,
        R.drawable.youja
    )

    val name = arrayOf(
        "암바사",
        "박카스",
        "갈아만든배",
        "바나나맛우유",
        "베지밀",
        "비타500",
        "보성녹차",
        "초코에몽",
        "코카콜라",
        "코코팜",
        "컨피던스",
        "데미소다",
        "도라지",
        "환타",
        "가나초코라떼",
        "조지아오리지널",
        "초록매실",
        "꿀홍삼",
        "핫식스",
        "제주오렌지",
        "레몬에이드",
        "맥콜",
        "밀키스",
        "미닛메이드",
        "모과생강",
        "마운틴듀",
        "옥수수 수염차",
        "오란씨",
        "포카리스웨트",
        "파워에이드",
        "2%",
        "사이다",
        "비락식혜",
        "스프라이트",
        "써니텐",
        "탑씨",
        "웰치스",
        "유자"
    )
}